wxread:
  # 微信活动链接
  wechat:
    infinite: https://weread.qq.com/wrpage/infinite/lottery
    jizan: https://weread.qq.com/book-detail?type=1&v=230326e071c69cda230127c&wtype=giveOneGetOneNewYear
  # 瓦斯组队提交链接
  commit:
    infinite: https://weread.qnmlgb.tech/submit
    jizan: https://weread.qnmlgb.tech/giveonegetone/submit
  # 用户 id
  vids:
    - "vid1"
    - "vid2"
    - "vid3"

clockin:
  userids:
    - "userid1"
    - "userid2"

# 企业微信api
workweixin:
  appinfo:
    corpid: corpid
    corpsecret: corpsecret
    agentid: 1000002
