wxread:
  # 微信活动链接
  wechat:
    infinite: https://weread.qq.com/wrpage/infinite/lottery
    jizan: https://weread.qq.com/wrpage/huodong/abtest/jizan
    flip: https://weread.qq.com/wrpage/flip/card
  # 瓦斯组队提交链接
  commit:
    infinite: https://weread.qnmlgb.tech/submit
    jizan: https://weread.qnmlgb.tech/giveonegetone/submit
    flip: https://weread.qnmlgb.tech/flip/submit
  # server酱push
  serverPush: https://sc.ftqq.com/{TOKEN}.send
  # 用户 id
  vids:
    - '35016575'
    - '36064827'
    - '21532019'
